// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT1JOUOecrCVhdgcFItp8CwdLLRIMepgk',
    appId: '1:779278133352:android:6891209dcf4ea98978f3dd',
    messagingSenderId: '779278133352',
    projectId: 'what-s-in-my-fridge-app',
    storageBucket: 'what-s-in-my-fridge-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_A60tD3Q5KgQ_1SfjBG11EzSbTmh6BZQ',
    appId: '1:779278133352:ios:2ceae0297c0c4ef378f3dd',
    messagingSenderId: '779278133352',
    projectId: 'what-s-in-my-fridge-app',
    storageBucket: 'what-s-in-my-fridge-app.appspot.com',
    iosClientId:
        '779278133352-ueqla14p7qt9ak61aheed9sn7oaflaid.apps.googleusercontent.com',
    iosBundleId: 'ntnu.idata2503.group6.whatsInMyFridge',
  );
}
